// Generated by scripts/gen-theme.py from
// comms/shared/theming/lex-theme.json. Do not edit by hand.
//
// Lex Monochrome rules + fallback palette consumed by
// src/monaco/theme.ts. The runtime prefers CSS variables when
// available (so light/dark switches don't need a regenerate);
// FALLBACK_PALETTES is used when CSS vars cannot be read.

export type Intensity = 'normal' | 'muted' | 'faint' | 'faintest'
export type BackgroundKey = 'code_bg'

export interface ColorPalette {
  normal: string
  muted: string
  faint: string
  faintest: string
  code_bg: string
}

export interface TokenRule {
  token: string
  intensity: Intensity
  fontStyle?: string
  background?: BackgroundKey
}

export const FALLBACK_PALETTES: { light: ColorPalette; dark: ColorPalette } = {
  light: {
    normal: '#000000',
    muted: '#808080',
    faint: '#b3b3b3',
    faintest: '#cacaca',
    code_bg: '#f5f5f5',
  },
  dark: {
    normal: '#e0e0e0',
    muted: '#888888',
    faint: '#666666',
    faintest: '#555555',
    code_bg: '#2a2a2a',
  },
}

export const TOKEN_RULES: TokenRule[] = [
  { token: 'DocumentTitle', intensity: 'normal', fontStyle: 'bold underline' },
  { token: 'DocumentSubtitle', intensity: 'normal', fontStyle: 'italic' },
  { token: 'SessionTitleText', intensity: 'normal', fontStyle: 'bold' },
  { token: 'SessionMarker', intensity: 'muted', fontStyle: 'italic' },
  { token: 'DefinitionSubject', intensity: 'normal', fontStyle: 'italic' },
  { token: 'DefinitionContent', intensity: 'normal' },
  { token: 'ListMarker', intensity: 'muted', fontStyle: 'italic' },
  { token: 'ListItemText', intensity: 'normal' },
  { token: 'InlineStrong', intensity: 'normal', fontStyle: 'bold' },
  { token: 'InlineEmphasis', intensity: 'normal', fontStyle: 'italic' },
  { token: 'InlineCode', intensity: 'normal' },
  { token: 'InlineMath', intensity: 'normal', fontStyle: 'italic' },
  { token: 'Reference', intensity: 'muted', fontStyle: 'underline' },
  { token: 'ReferenceCitation', intensity: 'muted', fontStyle: 'underline' },
  { token: 'ReferenceFootnote', intensity: 'muted', fontStyle: 'underline' },
  { token: 'ReferenceAnnotation', intensity: 'muted', fontStyle: 'underline' },
  { token: 'AnnotationLabel', intensity: 'faint' },
  { token: 'AnnotationParameter', intensity: 'faint' },
  { token: 'AnnotationContent', intensity: 'faint' },
  { token: 'VerbatimSubject', intensity: 'faint' },
  { token: 'VerbatimLanguage', intensity: 'faint' },
  { token: 'VerbatimAttribute', intensity: 'faint' },
  { token: 'VerbatimContent', intensity: 'normal', background: 'code_bg' },
  { token: 'InlineMarker_strong_start', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_strong_end', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_emphasis_start', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_emphasis_end', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_code_start', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_code_end', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_math_start', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_math_end', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_ref_start', intensity: 'faintest', fontStyle: 'italic' },
  { token: 'InlineMarker_ref_end', intensity: 'faintest', fontStyle: 'italic' },
]
