// Generated by scripts/gen-theme.py from
// comms/shared/theming/lex-theme.json. Do not edit by hand.
//
// Lex Monochrome rules + palette, pre-resolved per mode. Consumed
// by src/monaco/theme.ts. All colors are absolute hex strings
// resolved from canonical intensity/background tiers at generate
// time — no runtime indirection.

export interface ColorPalette {
  normal: string
  muted: string
  faint: string
  faintest: string
  code_bg: string
}

export interface TokenRule {
  token: string
  foreground: string
  fontStyle?: string
  background?: string
}

export const PALETTE: { light: ColorPalette; dark: ColorPalette } = {
  light: {
    normal: '#000000',
    muted: '#808080',
    faint: '#b3b3b3',
    faintest: '#cacaca',
    code_bg: '#f5f5f5',
  },
  dark: {
    normal: '#e0e0e0',
    muted: '#888888',
    faint: '#666666',
    faintest: '#555555',
    code_bg: '#2a2a2a',
  },
}

export const RULES: { light: TokenRule[]; dark: TokenRule[] } = {
  light: [
    { token: 'DocumentTitle', foreground: '000000', fontStyle: 'bold underline' },
    { token: 'DocumentSubtitle', foreground: '000000', fontStyle: 'italic' },
    { token: 'SessionTitleText', foreground: '000000', fontStyle: 'bold' },
    { token: 'SessionMarker', foreground: '808080', fontStyle: 'italic' },
    { token: 'DefinitionSubject', foreground: '000000', fontStyle: 'italic' },
    { token: 'DefinitionContent', foreground: '000000' },
    { token: 'ListMarker', foreground: '808080', fontStyle: 'italic' },
    { token: 'ListItemText', foreground: '000000' },
    { token: 'InlineStrong', foreground: '000000', fontStyle: 'bold' },
    { token: 'InlineEmphasis', foreground: '000000', fontStyle: 'italic' },
    { token: 'InlineCode', foreground: '000000' },
    { token: 'InlineMath', foreground: '000000', fontStyle: 'italic' },
    { token: 'Reference', foreground: '808080', fontStyle: 'underline' },
    { token: 'ReferenceCitation', foreground: '808080', fontStyle: 'underline' },
    { token: 'ReferenceFootnote', foreground: '808080', fontStyle: 'underline' },
    { token: 'ReferenceAnnotation', foreground: '808080', fontStyle: 'underline' },
    { token: 'AnnotationLabel', foreground: 'b3b3b3' },
    { token: 'AnnotationParameter', foreground: 'b3b3b3' },
    { token: 'AnnotationContent', foreground: 'b3b3b3' },
    { token: 'VerbatimSubject', foreground: 'b3b3b3' },
    { token: 'VerbatimLanguage', foreground: 'b3b3b3' },
    { token: 'VerbatimAttribute', foreground: 'b3b3b3' },
    { token: 'VerbatimContent', foreground: '000000', background: 'f5f5f5' },
    { token: 'InlineMarker_strong_start', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_strong_end', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_emphasis_start', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_emphasis_end', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_code_start', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_code_end', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_math_start', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_math_end', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_ref_start', foreground: 'cacaca', fontStyle: 'italic' },
    { token: 'InlineMarker_ref_end', foreground: 'cacaca', fontStyle: 'italic' },
  ],
  dark: [
    { token: 'DocumentTitle', foreground: 'e0e0e0', fontStyle: 'bold underline' },
    { token: 'DocumentSubtitle', foreground: 'e0e0e0', fontStyle: 'italic' },
    { token: 'SessionTitleText', foreground: 'e0e0e0', fontStyle: 'bold' },
    { token: 'SessionMarker', foreground: '888888', fontStyle: 'italic' },
    { token: 'DefinitionSubject', foreground: 'e0e0e0', fontStyle: 'italic' },
    { token: 'DefinitionContent', foreground: 'e0e0e0' },
    { token: 'ListMarker', foreground: '888888', fontStyle: 'italic' },
    { token: 'ListItemText', foreground: 'e0e0e0' },
    { token: 'InlineStrong', foreground: 'e0e0e0', fontStyle: 'bold' },
    { token: 'InlineEmphasis', foreground: 'e0e0e0', fontStyle: 'italic' },
    { token: 'InlineCode', foreground: 'e0e0e0' },
    { token: 'InlineMath', foreground: 'e0e0e0', fontStyle: 'italic' },
    { token: 'Reference', foreground: '888888', fontStyle: 'underline' },
    { token: 'ReferenceCitation', foreground: '888888', fontStyle: 'underline' },
    { token: 'ReferenceFootnote', foreground: '888888', fontStyle: 'underline' },
    { token: 'ReferenceAnnotation', foreground: '888888', fontStyle: 'underline' },
    { token: 'AnnotationLabel', foreground: '666666' },
    { token: 'AnnotationParameter', foreground: '666666' },
    { token: 'AnnotationContent', foreground: '666666' },
    { token: 'VerbatimSubject', foreground: '666666' },
    { token: 'VerbatimLanguage', foreground: '666666' },
    { token: 'VerbatimAttribute', foreground: '666666' },
    { token: 'VerbatimContent', foreground: 'e0e0e0', background: '2a2a2a' },
    { token: 'InlineMarker_strong_start', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_strong_end', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_emphasis_start', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_emphasis_end', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_code_start', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_code_end', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_math_start', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_math_end', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_ref_start', foreground: '555555', fontStyle: 'italic' },
    { token: 'InlineMarker_ref_end', foreground: '555555', fontStyle: 'italic' },
  ],
}
