#!/usr/bin/env python3
"""Generate src/monaco/theme-data.ts from the canonical theme data in
`comms/shared/theming/lex-theme.json`.

Emits two structures:

- FALLBACK_PALETTES: the 4 intensity tiers + code_bg, for both modes,
  used when CSS variables cannot be read (SSR, before document.body).
- TOKEN_RULES: the token → {intensity, fontStyle?, background?} map.
  The runtime in `theme.ts` resolves the intensity / background
  references against the live palette (CSS vars first, fallback
  otherwise) when defining the Monaco theme.

Splitting structure (here) from color values (resolved at runtime)
preserves the existing live-CSS-variable behavior while letting the
generator mirror the canonical schema 1:1.

Output style matches lexed's prettier config (no semicolons, single
quotes, tabWidth=2). Run after editing the canonical file. The npm
`theme:check` script runs `gen-theme.py --check`; pre-commit and
CI fail on stale output.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
CANONICAL = REPO_DIR / "comms" / "shared" / "theming" / "lex-theme.json"
TARGET = REPO_DIR / "src" / "monaco" / "theme-data.ts"


def s(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def font_style(token: dict) -> str | None:
    styles = token.get("styles", [])
    return " ".join(styles) if styles else None


EXPECTED_INTENSITIES = ("normal", "muted", "faint", "faintest")
EXPECTED_BACKGROUNDS = ("code_bg",)


def validate_canonical(canonical: dict) -> None:
    """The emitted TS hard-codes the Intensity / BackgroundKey / ColorPalette
    types. If the canonical schema grows or shrinks an intensity/background,
    the emitted TS will silently fail to typecheck. Fail loudly at generate
    time instead, so the divergence is obvious.

    Validation compares key sets (not key order), so a JSON formatter that
    reorders keys won't break this. Output order is still pinned to
    EXPECTED_INTENSITIES / EXPECTED_BACKGROUNDS in render() for stable diffs.
    """
    actual_intensities = set(canonical["intensities"].keys())
    expected_intensities = set(EXPECTED_INTENSITIES)
    if actual_intensities != expected_intensities:
        missing = [k for k in EXPECTED_INTENSITIES if k not in actual_intensities]
        unexpected = sorted(actual_intensities - expected_intensities)
        raise SystemExit(
            f"FAIL: canonical intensities must be exactly {list(EXPECTED_INTENSITIES)}.\n"
            f"      Missing: {missing}; unexpected: {unexpected}.\n"
            f"      Update Intensity / ColorPalette in this generator's render() "
            f"to match comms/shared/theming/lex-theme.json, then re-run."
        )
    actual_backgrounds = set(canonical.get("backgrounds", {}).keys())
    expected_backgrounds = set(EXPECTED_BACKGROUNDS)
    if actual_backgrounds != expected_backgrounds:
        missing = [k for k in EXPECTED_BACKGROUNDS if k not in actual_backgrounds]
        unexpected = sorted(actual_backgrounds - expected_backgrounds)
        raise SystemExit(
            f"FAIL: canonical backgrounds must be exactly {list(EXPECTED_BACKGROUNDS)}.\n"
            f"      Missing: {missing}; unexpected: {unexpected}.\n"
            f"      Update BackgroundKey / ColorPalette in this generator's render() "
            f"to match comms/shared/theming/lex-theme.json, then re-run."
        )


def render(canonical: dict) -> str:
    validate_canonical(canonical)
    intensities = canonical["intensities"]
    backgrounds = canonical.get("backgrounds", {})
    tokens = canonical["tokens"]

    def palette_block(mode: str) -> str:
        lines = []
        for name in EXPECTED_INTENSITIES:
            lines.append(f"    {name}: {s(intensities[name][mode])},")
        for bg_name in EXPECTED_BACKGROUNDS:
            lines.append(f"    {bg_name}: {s(backgrounds[bg_name][mode])},")
        return "\n".join(lines)

    rule_lines: list[str] = []
    for token_id, token in tokens.items():
        fields = [f"token: {s(token_id)}", f"intensity: {s(token['intensity'])}"]
        fs = font_style(token)
        if fs:
            fields.append(f"fontStyle: {s(fs)}")
        if "background" in token:
            fields.append(f"background: {s(token['background'])}")
        rule_lines.append("  { " + ", ".join(fields) + " },")

    return (
        "// Generated by scripts/gen-theme.py from\n"
        "// comms/shared/theming/lex-theme.json. Do not edit by hand.\n"
        "//\n"
        "// Lex Monochrome rules + fallback palette consumed by\n"
        "// src/monaco/theme.ts. The runtime prefers CSS variables when\n"
        "// available (so light/dark switches don't need a regenerate);\n"
        "// FALLBACK_PALETTES is used when CSS vars cannot be read.\n"
        "\n"
        "export type Intensity = 'normal' | 'muted' | 'faint' | 'faintest'\n"
        "export type BackgroundKey = 'code_bg'\n"
        "\n"
        "export interface ColorPalette {\n"
        "  normal: string\n"
        "  muted: string\n"
        "  faint: string\n"
        "  faintest: string\n"
        "  code_bg: string\n"
        "}\n"
        "\n"
        "export interface TokenRule {\n"
        "  token: string\n"
        "  intensity: Intensity\n"
        "  fontStyle?: string\n"
        "  background?: BackgroundKey\n"
        "}\n"
        "\n"
        "export const FALLBACK_PALETTES: { light: ColorPalette; dark: ColorPalette } = {\n"
        "  light: {\n"
        f"{palette_block('light')}\n"
        "  },\n"
        "  dark: {\n"
        f"{palette_block('dark')}\n"
        "  },\n"
        "}\n"
        "\n"
        "export const TOKEN_RULES: TokenRule[] = [\n"
        + "\n".join(rule_lines)
        + "\n]\n"
    )


def main() -> int:
    if not CANONICAL.exists():
        print(
            f"FAIL: canonical theme not found at {CANONICAL.relative_to(REPO_DIR)}.\n"
            f"      Did you forget `git submodule update --init`?",
            file=sys.stderr,
        )
        return 1

    canonical = json.loads(CANONICAL.read_text(encoding="utf-8"))
    expected = render(canonical)
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"FAIL: {TARGET.relative_to(REPO_DIR)} missing", file=sys.stderr)
            return 1
        # Normalize CRLF→LF so a Windows checkout that rewrote line endings
        # doesn't false-fail this comparison.
        actual = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual != expected:
            print(
                f"FAIL: {TARGET.relative_to(REPO_DIR)} out of sync.\n"
                f"      Run: python3 scripts/gen-theme.py",
                file=sys.stderr,
            )
            return 1
        print(f"  ✓ {TARGET.relative_to(REPO_DIR)} matches generator")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
